### ISSUE TITLE
Small changes in     looti/notebooks  /create_emulator_kz.ipynb

### ISSUE THREAD

**Issue by santiagocasas** [santiagocasas/looti-test-public#20]
The ratio_mode option in data_handle.py is old and unnecessary. Remove this from the class.

**Comment by santiagocasas** [comment]
Change it to normalize_by_reference.

**Comment by santiagocasas** [comment]
Remove this line from `z_list = list(np.loadtxt('../../input4cast/output/mg_camb_lhs_log10fR0/0000/z_values_list.txt'))     # list of available redshifts` repo.

**Comment by santiagocasas** [comment]
For training in z, take 90  `redshifts used for training`, equally spaced within the 100 z_samples. Test on the 10 in between samples.

**Comment by santiagocasas** [comment]
`nparam = 8` should be automatic and read from the pandas.

**Comment by santiagocasas** [comment]
`n_splits = 1                                    # Number of splits`   We will not need this in the near future, so remove from nb and use default.

**Comment by santiagocasas** [comment]
train_redshift_indices=list(range(5)),
test_redshift_indices=list(range(5))

inside the call to PredictRatio, should not be there and be created/called automatically.

**Comment by schafmeister** [comment]
Created new notebook to train and test emulators using cosmo_emulator.py
