### ISSUE TITLE
Data path and emulator path for the cosmo_emulator class should be unified and requested only once

### ISSUE THREAD

**Issue by santiagocasas** [santiagocasas/looti-test-public#22]
Data path and emulator path for the cosmo_emulator class should be unified and requested only once

No need for passing long dictionaries with each path

**Comment by schafmeister** [comment]
Changed so only one directory has to be given.
read_emulator now takes the directory and the observable name (cosmo_quantity) as input.
Trained emulators just have to be saved in the same directory and named according to the observable.
