### ISSUE TITLE
Implement better normalization of input spectra

### ISSUE THREAD

**Issue by santiagocasas** [santiagocasas/looti-test-public#4]
Implement a normalization of spectra, where they are divided by mean and then by st_dev, bin per bin.

**Comment by schafmeister** [comment]
Done in 63cfd61c10f916b9e47e1815956387ac1eaa816d

Introduced parameter "mean_std_norm" in datahandle. 

In line 190 calculate_ratio_by_redshift now takes mean_std_norm as argument and passes it on to calculate_ratio_data which is called in line 211.

For mean_std_norm=True, the normalization is carried out in calcluate_ratio_data  in lines 257-268:

`        if mean_std_norm == True:

            for nnoi in self.noise_names:

                # if ratio mode is not used, the spectra are divided by a reference spectrum
                if self.ratio_mode == True:
                    reftheo = 1
                else:
                    reftheo = self.df_ref.loc[(self.noiseless_str,z_request)].values

                exnoi = self.df_ext.loc[nnoi, z_request].values / reftheo

                # binwise normalization: we shift by the mean and divide by standard devitaion
                if normalize == True:
                    binwise_mean = exnoi.mean(axis=0)
                    binwise_std = exnoi.std(axis=0)
                else:
                    binwise_mean = 0
                    binwise_std = 1

                self.binwise_mean = binwise_mean
                self.binwise_std = binwise_std

                matrix_z[nnoi] = (exnoi - binwise_mean) / binwise_std`

To do: 
- delete old normalization which was handled with the parameter "normalization"
- change the way "ratio_mode" and "mean_std_norm" is handled to make it more intuitive

**Comment by santiagocasas** [comment]
Solved by MR #12
