### ISSUE TITLE
Implement normalization of PCA components

### ISSUE THREAD

**Issue by santiagocasas** [santiagocasas/looti-test-public#5]
Implement a normalization of PCA components, where they are divided by mean and then by st_dev, bin per bin.

**Comment by schafmeister** [comment]
Done in 63cfd61c10f916b9e47e1815956387ac1eaa816d

Introduced a parameter "pca_norm" in looti/dictlearn.py

PCAtraining now takes pca_norma as argument (line 158)

The normalization is then carried in lines 159-163 by subtraciting the mean of each component and dividing by the standard deviation. 

Predict_ratio (line 440), predict (line 243) and reconstruct_data (line 289) both take pca_norm as argument.

In reconstruct_data the normalization is reversed in lines 298-302 by multilying with the standard deviation and adding the mean.

**Comment by santiagocasas** [comment]
Solved by #12
