### ISSUE TITLE
Fix the GP Kernels

### ISSUE THREAD

**Issue by santiagocasas** [santiagocasas/looti-test-public#6]
- [x] Remove the White Kernel
- [x] Correct the Ynoise (alpha) (no square)
- [x] Remove the Constant Kernels 
- [x] RBF use default bounds (and make the bounds optional attributes)
- [x] N-dimensional length_scale for RBF, (use array of ones) -> make anisotropic
- [x] Increase n_restarts to 40 and test with different number of n_pca against bounds and theta: https://scikit-learn.org/stable/modules/gaussian_process.html#gaussian-process-kernel-api
- [x] Expose all these hyperparameters to the looti user

**Comment by schafmeister** [comment]
Done in 85637c2924e85f70996a5e0f87b6e7bd90a9d199

In looti/dictlearn.py:

Lines 17: removed unnecessary imports as we are only using the RBF kernel now

Line 45: changed default for gp_length to 6-dimensional array to make the kernel anisotropic
Line 46: added parameter gp_bounds and set default to scikit default bounds

Lines 60-105: added gp_bounds and removed bug where value of gp_const was written into variable gp_length

Line 227: removed constant kernels and white kernel, made gp bounds optional parameter
Line 229: correct alpha (removed square)

Lines 456-457: changed default for gp_length (to make kernel anisotropic) and added gp_bound with default values

Line 704: also removed the constant kernel in Interpolate_over_factor althought this function is not really useful anymore

**Comment by santiagocasas** [comment]
Solved by #12
